package dev.teamfive.tutoring.controller;

import java.io.IOException;

import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.resource.PathResourceResolver;

// NOTE: This is all blatantly generated by AI because I've never done this before and would have no idea how to do it otherwise.
@Configuration
public class WebConfig implements WebMvcConfigurer
{
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry)
    {
        registry.addResourceHandler("/**") // valid pattern
                .addResourceLocations("classpath:/static/") // React build files go here
                .resourceChain(true).addResolver(new PathResourceResolver()
                {
                    @Override
                    protected Resource getResource(String resourcePath, Resource location) throws IOException
                    {
                        // Prevent static resource handler from hijacking API calls
                        // resourcePath typically does NOT start with a leading slash
                        if (resourcePath == null)
                        {
                            return null;
                        }
                        String path = resourcePath.startsWith("/") ? resourcePath.substring(1) : resourcePath;
                        if (path.startsWith("api/"))
                        {
                            // return null so the request can be handled by controllers mapped to /api/**
                            return null;
                        }

                        Resource requested = location.createRelative(resourcePath);

                        // If the file exists, return it; otherwise, fall back to index.html
                        return (requested.exists() && requested.isReadable()) ? requested : new ClassPathResource("/static/index.html");
                    }
                });
    }
}
